[versions]
api-version = "1.20.1-R0.1-SNAPSHOT"

[libraries]
spigot = { module = "org.spigotmc:spigot-api", version.ref = "api-version" }
folia = { module = "dev.folia:folia-api", version.ref = "api-version" }