[versions]
api-version = "1.20.1-R0.1-SNAPSHOT"

[libraries]
spigot = { module = "org.spigotmc:spigot-api", version.ref = "api-version" }
folia = { module = "dev.folia:folia-api", version.ref = "api-version" }

[plugins]
licenser = "dev.yumi.gradle.licenser:2.1.1"
publish = "com.vanniktech.maven.publish:0.31.0"
dokka = "org.jetbrains.dokka:2.0.0"